### ISSUE TITLE
Wifi usage and mobile Data Drain 

### ISSUE THREAD

**Issue by hackerx1001** [declangao/WordpressReader#3]
I'm facing this problem where the app is draining mobile and WiFi data. 
Is it because the app doesn't save anything to the cache because it reloading the images all again each time you close the app 
Please help

**Comment by declangao** [comment]
Yes. Volley's default image caching mechanism is in-memory cache. 
You can use Glide lib (https://github.com/bumptech/glide) instead of NetworkImageView that comes with Volley to load images for better caching.
I'm planning on switching to OkHttp and Glide for this project for reasons like this. But if you can't wait, it's very straight forward to do it yourself.

**Comment by declangao** [comment]
Just pushed a commit with disk image cache support.

**Comment by hackerx1001** [comment]
thanks alot, and can you write me the code to support wordpress own comments function ?
