### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by rebelholic** [declangao/WordpressReader#5]
Thanks for awesome reader but I've got some encountered error when testing with [my blog](http://unity3dindonesia.com/):
1. Its cannot show full article for one single page but must click "Read More" to show full article on native browser like my screenshot below:
   ![error app](https://cloud.githubusercontent.com/assets/6254876/9412071/00b5de56-4854-11e5-9248-bb9acc60298c.jpg)
   How I can fix it?
2. Also it cannot support full load for CSS and JS if I am using [Jetpack Plugin](http://jetpack.me/support/publicize/) for sharing option like screenshot below
   ![sharing option](https://cloud.githubusercontent.com/assets/6254876/9412318/38547c04-4855-11e5-86c1-0297f86695b0.jpg)
3. How I can integrate with woocommerce plugin?

I am tested on emulator device with Android Mashmallow OS not on real device

**Comment by declangao** [comment]
1. I had a look at the result returned by JSON API plugin on your site. http://unity3dindonesia.com/?json=get_recent_posts seems to return the excerpt of a post instead of full content in the "content" field. This may be the intended behaviour. I'm not quite sure. Never tried it on a site with excerpt enabled. I guess you can modify the code a bit to request full content with a url like http://unity3dindonesia.com/?json=get_post&id=25 inside PostFragment. All you need is an ID, which you already have.
2. Can you give me a bit more details on this issue?
3. I have never used Woocommerce. But it looks like integrating with it requires a lot of work. Dealing pages is most likely required. As this app is only intended to read posts, I'm not planning on adding support for pages any time soon. But as long as you know the url to buy an item or to check out, you can always add menu or button to perform the action instead of rendering HTML content in a WebView. This is just my initial thought anyway.

**Comment by rebelholic** [comment]
1. Could you give me a guide about to get an ID with automatically so it will show full content for next page?
2.  I guess its problem from my emulator cannot support full load for css and js and I can fix it with myself.

**Comment by declangao** [comment]
It's kinda similiar to the loadCategories() method in TabLayoutFragment. Only the URL you need to request is something like this, http://unity3dindonesia.com/?json=get_post&id=25. You already have access to the ID of each post since it's passed to the fragment through Bundle. Also, you need to parse JSON data returned from the server. Slight modification to the JSONParser class will do the job.

**Comment by aziz120** [comment]
good evening you can help me comment does not function in..CommentFragment.java

```
            // Create Disqus ID Thread help plez  mi email : thonons72@gmail.com
```
