### ISSUE TITLE
xml error

### ISSUE THREAD

**Issue by horllste** [declangao/WordpressReader#6]
Hello, please i got an error here
    <style name="Base.AppTheme" parent="Theme.AppCompat.NoActionBar">

am new to java, am using google API android 6.0, API 23.

please what did i do wrong

**Comment by declangao** [comment]
What error? Give me the error msg at least.

**Comment by horllste** [comment]
this is what i got in the console
git\WordpressReader\app\src\main\res\values\styles.xml:26: error: Error retrieving parent for item: No resource found that matches the given name 'TextAppearance.Design.Tab'.

kindly put me through on how to fix it.
thanks

**Comment by declangao** [comment]
I think you are missing the support library. Please install support libs in your SDK manager first and see if that solves the problem.

**Comment by horllste** [comment]
i have the support library, i will check again and give you the exact error

**Comment by horllste** [comment]
you have change the project package, trying to build it with gradle now

**Comment by clarisi** [comment]
Hi, I'm new in android programmation (I'm not programming a few years ago because I had a baby!!!) Now I'm trying to implement a navigation drawer in your wordpress reader project. I'm getting crazy.  My navigation drawer appears below cardview posts and I can't interact with it or the tool bar disappears completely!!!

Can you help me to insert navigation drawer in the right place???!!!

Than you so much!!!
